language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_deps"
- "./travis-tool.sh install_r microbenchmark knitr arules testthat timeDate"
- "./travis-tool.sh install_github robertzk/statsUtils robertzk/stagerunner robertzk/mungebits
  robertzk/Ramd robertzk/testthatsomemore"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: fbnQudMK1iKkiIvCBDZ9NCCf0GjcwCgGAlL0mXlLJ/sHhN+/OnzL4BmFXLGnvJhUL/D5sBIZxnxPTTZunx7favJ6wiruRo82exekDShsB2LIxdT9cxBDzPvo6yQEdGX9xRkhMfKDEN86g+aFqEqYmLy+2B8P1LSQCHsaCfFbnXc=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
